import styles from './page.module.scss';

export const metadata = {
  title: 'hello Gdd',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className={styles.title}>这里是titleBar</div>
        {children}
      </body>
    </html>
  )
}
